package cn.heknd.scanner;

//token序列的定义《type,context》
public enum Words
{
	PROGRAM,TYPE,VAR,PROCEDURE,BEGIN,END,ARRAY,OF,RECORD,IF,THEN,
	ELSE,FI,WHILE,DO,ENDWH,READ,WRITE,RETURN,INTEGER,CHAR,
	
	UNSIGNEDNUMBER,
	
	ADD,SUB,MUL,DIV,LESS,EQUAL,LEFT_PARENT,RIGHT_PARENT,
	LEFT_BRACKET,RIGHT_BRACKET,DOT,SEMICOLON,EOF,SPACE,
	COLON_EQUAL,LEFT_BRACES,RIGHT_BRACES,APOSTROPHE,TWO_DOT,
	
	COMMA,
	
	IDENTIFIERS;
}